site_name: Regular Expression

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math

pages:
  - 'Introduction': 'index.md'
  - 'Quatifiers': 'quantifiers.md'